---
- name: Install and configure Docker, PostgreSQL, Node.js, and React
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - unzip

    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install PostgreSQL client package
      ansible.builtin.package:
        name: postgresql
        state: latest

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: latest

    - name: Install npm
      ansible.builtin.package:
        name: npm
        state: latest

    - name: Install React dependencies
      ansible.builtin.command:
        cmd: "npm install -g create-react-app"

- name: Postgres database configuration
  hosts: _ansible_postgresql
  become: true
  vars:
    container_name: postgre
    image_name: insaniso/postgre:latest
  tasks:
    - name: Remove Postgres container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Remove Postgres image
      community.docker.docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: Launch Postgresql Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "Pp123456789"
        volumes:
          - /db-data:/var/lib/postgresql/data

- name: Node.js Server configuration
  hosts: _ansible_nodejs
  become: true
  vars:
    container_name: nodejs
    image_name: insaniso/nodejs:latest
  tasks:
    - name: Remove Node.js container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Remove Node.js image
      community.docker.docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: Launch Node.js Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "5000:5000"

- name: React UI Server configuration
  hosts: _ansible_react
  become: true
  vars:
    container_name: react
    image_name: insaniso/react:latest
  tasks:
    - name: Remove React container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Remove React image
      community.docker.docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: Launch React Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "3000:3000"
